Removing PR creation mechanism
redhat-appstudio/clair-in-ci-db pull request #9
Opened 2023-10-06 08:57 UTC by jsztuka

Triggering tekton CI can be achieved by simply creating an empty commit each day on scheduled basis.
That is the reason why we don't need complicated PR creation(opening/closing) mechanism.
Its also triggering image builds duplicitly.

2023-10-06 08:59 UTC, jsztuka commented
Updated commit msg, should be updated any time now.

2023-10-06 12:43 UTC, MartinBasti approved these changes

2023-10-06 12:45 UTC, MartinBasti requested changes
https://github.com/redhat-appstudio/clair-in-ci-db/blob/441c4d48b87cbf421047e7d674b657826473024c/.tekton/build_and_trigger.yaml#L80

This file should be also updated and code for daily updates removed

2023-10-10 12:14 UTC, MartinBasti approved these changes

2023-10-11 09:04 UTC, dirgim approved these changes
LGTM

2023-10-11 09:36 UTC, merged